### ISSUE TITLE
有个小bug

### ISSUE THREAD

**Issue by ewen0930** [drawcall/ppo#1]
带 option的 setCookie报错！
289行 和317行， expires 改 str 才对

**Comment by ewen0930** [comment]
ppo.isIE() ppo.ieVersion() 对IE11无效，IE11检测Trident和rv
function IETester() {
    var UA = navigator.userAgent;
    if (/msie/i.test(UA)) {
        return parseFloat(UA.match(/msie (\d+\.\d+)/i)[1]);
    } else if (~UA.toLowerCase().indexOf('trident') && ~UA.indexOf('rv')) {
        return parseFloat(UA.match(/rv:(\d+\.\d+)/)[1]);
    }
    return -1;
}

**Comment by drawcall** [comment]
ok thinks zan

**Comment by drawcall** [comment]
还没有测试，先建了个项目。帮忙测试哈

**Comment by ewen0930** [comment]
感觉很实用，就大致测了一遍，没发现其他问题！准备以后用；文档的getCookie示例敲错了

**Comment by drawcall** [comment]
多谢 ie detect已经修复
